export default {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'EUV Lithography Guide',
      items: [
        'chapters/intro',
        'chapters/photolithography-basics', 
        'chapters/why-euv-rayleigh',
        // Add more chapters as they are converted to MDX
        {
          type: 'autogenerated',
          dirName: 'chapters',
        },
      ],
    },
  ],
};